name: Build Tailsshport Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            ext: ''
          - os: windows-latest
            platform: windows
            ext: '.exe'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install system dependencies (Linux)
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          sshpass \
          libsecret-1-dev \
          gnome-keyring \
          libdbus-1-dev \
          libx11-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install keyring \
                    argparse \
                    setuptools

    - name: Build executable
      run: |
        pyinstaller --onefile \
                    --name tailsshport${{ matrix.ext }} \
                    --add-data "README.md:." \
                    --hidden-import=keyring.backends.SecretService \
                    --hidden-import=keyring.backends.kwallet \
                    --hidden-import=keyring.backends.Windows \
                    --hidden-import=keyring.backends.macOS \
                    tailsshport.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tailsshport-${{ matrix.platform }}
        path: |
          dist/tailsshport${{ matrix.ext }}
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/tailsshport-linux/tailsshport
          artifacts/tailsshport-windows/tailsshport.exe
        tag_name: v0.1.0-${{ github.sha }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
